const ROOT = 'http://localhost:3000/api'

export const PRODUCTS_ROOT = `${ROOT}/product`
export const ADDRESS_ROOT = `${ROOT}/address`
export const AREAS_ROOT = `${ROOT}/area`
export const BRANDS_ROOT = `${ROOT}/brand`
export const CASHS_ROOT = `${ROOT}/cashs`
export const CATEGORIES_ROOT = `${ROOT}/category`
export const TYPES_ROOT = `${ROOT}/type`
export const CITIES_ROOT = `${ROOT}/city`
export const DEPARTMENTS_ROOT = `${ROOT}/department`
export const GENRES_ROOT = `${ROOT}/genre`
export const CLIENTS_ROOT = `${ROOT}/client`
export const CREDENTIALS_ROOT = `${ROOT}/credential`
export const DISTRICS_ROOT = `${ROOT}/district`
export const EMPLOYEES_ROOT = `${ROOT}/employee`
export const POSITIONS_ROOT = `${ROOT}/position`
export const PAYMENT_METHODS_ROOT = `${ROOT}/payment-method`
export const PRODUCT_INFOS_ROOT = `${ROOT}/product-infos`
export const PRODUCT_SALES_ROOT = `${ROOT}/product-sales`
export const PROFILE_ROOT = `${ROOT}/profile`
export const PROVIDERS_ROOT = `${ROOT}/provider`
export const PURCHASES_ROOT = `${ROOT}/purchase`
export const ORDER_ROOT = `${ROOT}/order`
export const SALE_POINTS_ROOT = `${ROOT}/sale-point`
export const TAGS_ROOT = `${ROOT}/tags`
export const TAG_DETAILS_ROOT = `${ROOT}/tag-detail`
export const INITIAL_PROMPT = 'Actúa como un asistente del sistema Atlas - Inventory. Saluda y presentate al usuario como Atlas. Solo responde preguntas relacionadas con el sistema Atlas - Inventory'
