const ROOT = 'http://localhost:3000/api'

export const PRODUCTS_ROOT = `${ROOT}/product`
export const ADDRESS_ROOT = `${ROOT}/addresses`
export const AREAS_ROOT = `${ROOT}/areas`
export const BRANDS_ROOT = `${ROOT}/brands`
export const CASHS_ROOT = `${ROOT}/cashs`
export const CATEGORIES_ROOT = `${ROOT}/categories`
export const CITIES_ROOT = `${ROOT}/cities`
export const CLIENTS_ROOT = `${ROOT}/clients`
export const CREDENTIALS_ROOT = `${ROOT}/credentials`
export const DISTRICS_ROOT = `${ROOT}/districts`
export const EMPLOYEES_ROOT = `${ROOT}/employees`
export const POSITIONS_ROOT = `${ROOT}/positions`
export const PRODUCT_INFOS_ROOT = `${ROOT}/product-infos`
export const PRODUCT_SALES_ROOT = `${ROOT}/product-sales`
export const PROFILES_ROOT = `${ROOT}/profiles`
export const PROVIDERS_ROOT = `${ROOT}/providers`
export const PURCHASES_ROOT = `${ROOT}/purchases`
export const SALES_ROOT = `${ROOT}/sales`
export const SALE_POINTS_ROOT = `${ROOT}/sale-points`
export const TAGS_ROOT = `${ROOT}/tags`
export const TAG_DETAILS_ROOT = `${ROOT}/tag-details`
